### ISSUE TITLE
TYPO3 v8 LTS (8.7) compatibility

### ISSUE THREAD

**Issue by webdev2027** [derhansen/femanager_dmail_subscribe#3]
Hi, is the TYPO3 8.7 compatibility planned? This would be great with the latest femanager and direct_mail (for 8.7).

**Comment by derhansen** [comment]
Support for TYPO3 8.7 is planned for the next few weeks, so a release can be published latest in january 2018.

**Comment by derhansen** [comment]
@webdev2027 I added TYPO3 8.7 compatibility. Would you mind testing the current master branch? and give me a short feedback?

**Comment by derhansen** [comment]
New version releases on TER
